name: Build Kivy APK

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y build-essential ccache git libncurses5 libstdc++6 libffi-dev libssl-dev libsqlite3-dev zlib1g-dev liblzma-dev libbz2-dev libreadline-dev openjdk-17-jdk python3-pip
          pip install --upgrade pip
          pip install buildozer

      - name: Initialize buildozer
        run: |
          buildozer init
          sed -i 's/^requirements = .*/requirements = kivy/' buildozer.spec
          sed -i 's/^# android\.ndk_path/\1/' buildozer.spec
          sed -i 's/^# android\.sdk_path/\1/' buildozer.spec

      - name: Copy main.py
        run: |
          mv main.py .

      - name: Build APK
        run: |
          buildozer android debug

      - name: Upload APK
        uses: actions/upload-artifact@v3
        with:
          name: kivy-debug-apk
          path: bin/*.apk
